Update workflow to replicate api platform for testing

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -13,84 +13,27 @@ env:
 
 jobs:
   docker-build-test-deploy:
-    name: Docker build/test/deploy (Docker ${{ matrix.docker }})
+    name: Test and Deploy
     runs-on: ubuntu-latest
-    container:
-      image: docker:${{ matrix.docker }}
-      env:
-        DOCKER_CERT_PATH: /certs/client
-        DOCKER_CLI_EXPERIMENTAL: enabled
-        DOCKER_HOST: tcp://docker:2376
-        DOCKER_TLS_VERIFY: '1'
-      options: >-
-        -v /tmp/docker/certs/client:/certs/client
-    services:
-      docker:
-        image: docker:${{ matrix.docker }}-dind
-        env:
-          DOCKER_TLS_CERTDIR: /certs
-        options: >-
-          --privileged
-          -v /home/runner/work:/__w
-          -v /tmp/docker/certs:/certs
-          --health-cmd "docker info"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-    strategy:
-      matrix:
-        docker:
-          - '20.10'
-      fail-fast: false
-    timeout-minutes: 10
+    timeout-minutes: 5
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Install system packages
-        run: |
-          apk add \
-            curl \
-            jq \
-      - name: Install Docker Buildx
-        run: |
-          mkdir -p ~/.docker/cli-plugins
-          curl -fsSL -o ~/.docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/v${DOCKER_BUILDX_VERSION}/buildx-v${DOCKER_BUILDX_VERSION}.linux-amd64"
-          chmod +x ~/.docker/cli-plugins/docker-buildx
-      - name: Install Docker Compose
-        run: |
-          docker create --name docker_compose "docker/compose:alpine-${DOCKER_COMPOSE_VERSION}"
-          docker cp docker_compose:/usr/local/bin/docker-compose /usr/local/bin/docker-compose
-          docker rm docker_compose
-      - name: Create builder instance
-        run: |
-          docker context create default_tls
-          docker buildx create --driver docker-container --driver-opt image=moby/buildkit:master,network=host --use default_tls
-      - name: Build images
-        # --set php.args.BUILDKIT_INLINE_CACHE=1 \
-        run: |
-          docker buildx bake \
-            --pull \
-            --set php.output=type=docker \
-            --set caddy.args.BUILDKIT_INLINE_CACHE=1 \
-            --set caddy.output=type=docker \
-            --set cache-proxy.args.BUILDKIT_INLINE_CACHE=1 \
-            --set cache-proxy.output=type=docker \
-      - name: Validate composer.json
-        run: |
-          if jq -e '.extra.symfony.id != null' api/composer.json > /dev/null; then
-            echo 'api/composer.json must not have extra.symfony.id' 1>&2
-            exit 1
-          fi
-          docker-compose run --no-deps --entrypoint '' --rm -T php composer validate --no-check-publish
+      - name: Pull images
+        run: docker compose pull --ignore-pull-failures || true
       - name: Start services
-        run: docker-compose up -d
+        run: docker-compose up --build -d
       - name: Wait for services
         run: |
-          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q php)")"; do
+          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
             case $status in
               starting) sleep 1;;
               healthy) exit 0;;
-              unhealthy) exit 1;;
+              unhealthy)
+                docker compose ps
+                docker compose logs
+                exit 1
+              ;;
             esac
           done
           exit 1
@@ -109,10 +52,22 @@ jobs:
           else
             sleep 1
           fi
-      # -f = fail silently
-      # -k = insecure
-      # -v = verbose
-      # -I = head, fetch headers only
+        # -f = fail silently
+        # -k = insecure
+        # -v = verbose
+        # -I = head, fetch headers only
+      - name: Check HTTP reachability
+        run: curl -v -o /dev/null http://localhost
+      - name: Check HTTPS reachability
+        run: curl  -vk -o /dev/null https://localhost
+      - name: Create test database
+        run: |
+          docker compose exec -T php bin/console -e test doctrine:database:create
+          docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
+      - name: PHPUnit
+        run: docker compose exec -T php bin/phpunit
+      - name: Doctrine Schema Validator
+        run: docker compose exec -T php bin/console doctrine:schema:validate --skip-sync
       - name: Copy container CA certificate
         run: |
           docker cp $(docker-compose ps -q caddy):/usr/local/share/ca-certificates /usr/local/share/ca-certificates
